import { pages, pageMetadata, courses } from "../lib/site";
import { Portrait, QuoteButton, TextLink, FinalCTA } from "../components/Shared";
export const metadata=pageMetadata(pages[0]);
export default function Home() {return <>
<section className="hero ea-container"><div className="hero-copy"><p className="eyebrow"><span className="small-cross" aria-hidden="true">+</span> ENSIAPUKOULUTUKSET · EASYEA</p><h1 className="ea-h1">Ensiapukoulutus,<br/>{" "}joka antaa <span className="highlight">rohkeutta</span> auttaa</h1><p className="ea-lead">{pages[0].lead}</p><div className="hero-actions"><QuoteButton/><TextLink href="/kurssit/">Tutustu ensiapukursseihin</TextLink></div><ul className="hero-facts">{["Ensihoitaja kouluttajana","Käytännön harjoittelua","Lähikoulutukset"].map(t=><li key={t}><span aria-hidden="true">✓</span>{t}</li>)}</ul></div><Portrait/></section>
<section className="trainer-intro ea-container ea-section split"><div><p className="eyebrow">IHMINEN KOULUTUKSEN TAKANA</p><h2 className="ea-h2">Opi ensiapua ihmisen kanssa, joka tekee sitä työkseen</h2></div><div><p>EasyEA:n kouluttaja Jami Nyholm työskentelee ensihoidossa. Hänen opetuksessaan alan osaaminen muuttuu ymmärrettäviksi kokonaisuuksiksi ja käytännön harjoitteluksi.</p><p>Kurssille saa tulla kysymään, kokeilemaan ja oppimaan. Tavoitteena on, että jokaisella osallistujalla on koulutuksen jälkeen enemmän varmuutta tarttua auttamiseen.</p><TextLink href="/kouluttaja/">Tutustu Jamiin</TextLink></div></section>
<section className="ea-section ea-container"><div className="section-heading"><div><p className="eyebrow">KURSSIT ERI TARPEISIIN</p><h2 className="ea-h2">Löydä ryhmällesi sopiva ensiapukurssi</h2></div><p>Tarvitsetteko tiiviin koulutuksen vai aikaa perehtyä ensiapuun laajemmin? Tutustu vaihtoehtoihin tai kerro ryhmänne tarpeesta. Autamme kurssin valinnassa.</p></div><div className="ea-courses">{courses.map((c,i)=><article className="ea-card ea-course-card" key={c.id}><div className="card-top"><span className="tag">{c.duration}</span><span className="course-number" aria-hidden="true">0{i+1}</span></div><h3 className="ea-h3">{c.name}</h3><p>{c.text}</p><TextLink href={`/kurssit/#${c.id}`}>{c.link}</TextLink></article>)}</div></section>
<section className="soft-section ea-section"><div className="ea-container split"><div><p className="eyebrow">YHDESSÄ OPPIMINEN</p><h2 className="ea-h2">Ensiapukoulutus yritykselle, seuralle tai yhteisölle</h2></div><div><p>Kun järjestät koulutusta ryhmälle, aloita osallistujamäärästä ja siitä, mitä haluatte oppia. Myös ryhmän aiempi osaaminen auttaa löytämään sopivan kokonaisuuden.</p><p>Vakiokurssien lisäksi EasyEA tarjoaa räätälöityjä koulutuksia. Kerro toiveesi, niin keskustellaan teille sopivasta vaihtoehdosta.</p><TextLink href="/ensiapukoulutus-yrityksille/">Lue yritysten ryhmäkoulutuksista</TextLink></div></div></section>
<section className="ea-container ea-section"><p className="eyebrow">HELPPO ALKU</p><h2 className="ea-h2">Näin pääsette alkuun</h2><ol className="steps">{[["Kerro ryhmästäsi","Lähetä osallistujamäärä, paikkakunta ja toivottu ajankohta. Kurssia ei tarvitse tietää valmiiksi."],["Etsitään sopiva kokonaisuus","Käydään läpi koulutustoiveenne ja sovitaan toteutuksen yksityiskohdat."],["Harjoitellaan yhdessä","Koulutuksessa ensiapuun tutustutaan ohjatusti ja käytännön kautta."]].map(([title,text],i)=><li key={title}><span className="step-number" aria-hidden="true">0{i+1}</span><h3 className="ea-h3">{title}</h3><p>{text}</p></li>)}</ol></section>
<section className="ea-container locality"><div><p className="eyebrow">LÄHELLÄSI</p><h2 className="ea-h2">Kouvolasta koko Suomeen</h2><p>EasyEA toimii Kouvolassa ja palvelee ryhmiä ympäri Suomea. Kysy koulutusta omalle paikkakunnallesi.</p><TextLink href="/ensiapukurssi-kouvola/">Ensiapukurssit Kouvolassa</TextLink></div><div className="locality-word" aria-hidden="true">Kouvola<span>→ koko Suomi</span></div></section><FinalCTA/>
</>;}
