"use client";
import { useState } from "react";
import Link from "next/link";
import { calculateBudget, calculateTierExample, exampleTiers, formatEuro, parseCount, type BudgetInput } from "../lib/budget";
import { trainingCourses, trainingLink, type TrainingContext, type CourseId } from "../lib/training";

const moneyFields = [
  {key:"training",label:"Koulutuksen hinta (€)",help:"Syötä koulutuksen ryhmä- tai henkilöhinta tarjouksesta."},
  {key:"certificate",label:"Todistusten lisämaksu / hlö (€)",help:"Syötä vain koulutushinnan ulkopuolinen maksu. Muuten 0."},
  {key:"travel",label:"Matkakulut yhteensä (€)",help:"Kaikkien koulutusryhmien matkakulut yhteensä."},
  {key:"other",label:"Muut lisäkulut yhteensä (€)",help:"Esimerkiksi erillinen tilavuokra. Muuten 0."},
] as const;

export function PriceCalculator({initial={}}:{initial?:TrainingContext}) {
  const [mode,setMode]=useState<"example"|"quote">("example");
  const [courseId,setCourseId]=useState<CourseId>(initial.courseId??"hataensiapu-4h");
  const [input,setInput]=useState<BudgetInput>({participants:String(initial.participants??12),groups:"1",unit:"group",training:"",certificate:"0",travel:"0",other:"0",includesVat:true,vat:""});
  const update=<K extends keyof BudgetInput>(key:K,value:BudgetInput[K])=>setInput(previous=>({...previous,[key]:value}));
  const calculated=calculateBudget(input);
  const example=calculateTierExample(input.participants);
  const validPeople=parseCount(input.participants);
  const course=trainingCourses.find(c=>c.id===courseId)!;
  const smallCustom=courseId==="raataloity"&&validPeople!==null&&validPeople<4;
  const context:TrainingContext={...initial,courseId,packageId:courseId===initial.courseId?initial.packageId:undefined,participants:validPeople??undefined};
  const showErrors=mode==="quote"&&input.training!=="";
  const activeErrors=mode==="example"?{}:calculated.errors;
  return <section className="ea-container ea-section calculator-section" id="laskuri" aria-labelledby="calculator-title">
    <div className="planner-heading"><p className="eyebrow">RYHMÄKOOSTA SELKEÄÄN HINTAAN</p><h2 className="ea-h2" id="calculator-title">Mitä koulutus maksaa osallistujaa kohti?</h2><p>Tutustu ryhmäkoon mukaiseen hinnoitteluesimerkkiin tai erittele saamasi tarjous omilla hinnoillasi.</p></div>
    <fieldset className="calculator-mode"><legend className="sr-only">Valitse laskurin käyttötapa</legend><label className={mode==="example"?"is-active":""}><input type="radio" name="calculator-mode" checked={mode==="example"} onChange={()=>setMode("example")}/>Hinnoitteluesimerkki</label><label className={mode==="quote"?"is-active":""}><input type="radio" name="calculator-mode" checked={mode==="quote"} onChange={()=>setMode("quote")}/>Vertaa saamaasi tarjousta</label></fieldset>
    {mode==="example"?<><div className="price-model-note"><strong>Esimerkkihinnoittelu</strong><p>99 / 79 / 59 € ovat hinnoittelumallin esimerkkihintoja. EasyEA:n koulutuksen hinta ja ALV-käsittely vahvistetaan tarjouksessa.</p></div><div className="tier-grid">{exampleTiers.map(t=><div className={`tier-card ${example?.tierMin===t.min?"is-selected":""}`} key={t.min}><span>{t.label}</span><strong>{formatEuro(t.price)} <small>/ hlö</small></strong><span className="tier-status">{example?.tierMin===t.min?"Valittu hintataso":"Ryhmäkoon mukainen hinta"}</span></div>)}</div></>:<p className="calculator-quote-note">Syötä tarjouksen hinnat ja vain niihin sisältymättömät lisäkulut. Laskuri ei hae hintoja kouluttajalta.</p>}
    <div className="calculator-layout"><div className="ea-card calculator-inputs"><div className="ea-form-grid"><div className="ea-field ea-field-full"><label className="ea-label" htmlFor="budget-course">Vertailtava kurssi</label><select id="budget-course" className="ea-select" value={courseId} onChange={e=>setCourseId(e.target.value as CourseId)}>{trainingCourses.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div className="ea-field ea-field-full"><label className="ea-label" htmlFor="budget-participants">Osallistujamäärä yhteensä</label><input id="budget-participants" className="ea-input" inputMode="numeric" value={input.participants} onChange={e=>update("participants",e.target.value)} aria-invalid={validPeople===null} aria-describedby="budget-participants-help"/><p id="budget-participants-help" className={validPeople===null?"ea-error":"ea-help"}>{validPeople===null?"Syötä kokonaisluku väliltä 1–10 000.":"Ryhmäjako ja koulutusryhmien koko sovitaan erikseen."}</p></div>
      {mode==="quote"?<><div className="ea-field"><label className="ea-label" htmlFor="budget-unit">Koulutushinnan yksikkö</label><select id="budget-unit" className="ea-select" value={input.unit} onChange={e=>update("unit",e.target.value as BudgetInput["unit"])}><option value="group">Hinta / koulutusryhmä</option><option value="person">Hinta / osallistuja</option></select></div>{input.unit==="group"?<div className="ea-field"><label className="ea-label" htmlFor="budget-groups">Koulutusryhmien määrä</label><input id="budget-groups" className="ea-input" inputMode="numeric" value={input.groups} onChange={e=>update("groups",e.target.value)} aria-invalid={!!activeErrors.groups} aria-describedby={activeErrors.groups?"budget-groups-error":undefined}/>{activeErrors.groups?<p id="budget-groups-error" className="ea-error">{activeErrors.groups}</p>:null}</div>:null}
      {moneyFields.map(f=><div className="ea-field" key={f.key}><label className="ea-label" htmlFor={`budget-${f.key}`}>{f.label}</label><input id={`budget-${f.key}`} className="ea-input" inputMode="decimal" value={input[f.key]} placeholder={f.key==="training"?"Syötä tarjouksen hinta":undefined} onChange={e=>update(f.key,e.target.value)} aria-invalid={showErrors&&!!activeErrors[f.key]} aria-describedby={`budget-${f.key}-help`}/><p id={`budget-${f.key}-help`} className={showErrors&&activeErrors[f.key]?"ea-error":"ea-help"}>{showErrors&&activeErrors[f.key]?activeErrors[f.key]:f.help}</p></div>)}
      <div className="ea-field ea-field-full"><label className="ea-label" htmlFor="budget-vat-mode">Syötetyt hinnat</label><select id="budget-vat-mode" className="ea-select" value={input.includesVat?"included":"excluded"} onChange={e=>update("includesVat",e.target.value==="included")}><option value="included">Sisältävät tarjouksen ALV:n</option><option value="excluded">Ilman ALV:tä – lisää tarjouksen veroprosentti</option></select></div>{!input.includesVat?<div className="ea-field ea-field-full"><label className="ea-label" htmlFor="budget-vat">Tarjouksen ALV (%)</label><input id="budget-vat" className="ea-input" inputMode="decimal" value={input.vat} onChange={e=>update("vat",e.target.value)} aria-invalid={showErrors&&!!activeErrors.vat} aria-describedby="budget-vat-help"/><p id="budget-vat-help" className={showErrors&&activeErrors.vat?"ea-error":"ea-help"}>{showErrors&&activeErrors.vat?activeErrors.vat:"Sama prosentti lisätään kaikkiin kuluihin. Jos tarjouksessa on eri verokantoja, tarkista erittely erikseen."}</p></div>:null}</>:null}</div><button type="button" className="calculator-reset ea-link" onClick={()=>setInput({participants:"12",groups:"1",unit:"group",training:"",certificate:"0",travel:"0",other:"0",includesVat:true,vat:""})}>Palauta lähtöarvot</button></div>
      <aside className="budget-summary" aria-labelledby="budget-summary-title"><p className="eyebrow">{mode==="example"?"HINNOITTELUMALLIN ESIMERKKI":"OMA TARJOUSVERTAILUSI"}</p><h3 className="ea-h3" id="budget-summary-title">{course.name}</h3><div className="budget-live" aria-live="polite" aria-atomic="true">{mode==="example"&&example?<><p className="budget-total-label">Mallin kokonaissumma</p><p className="budget-total">{formatEuro(example.total)}</p><p className="budget-person">{formatEuro(example.unitPrice)} / osallistuja</p><dl className="budget-breakdown"><div><dt>Osallistujat</dt><dd>{example.participants}</dd></div><div><dt>Hintataso</dt><dd>{formatEuro(example.unitPrice)} / hlö</dd></div></dl><p className="ea-help">Hintataso koskee koko ryhmää. Kun osallistujamäärä ylittää portaan, kaikkien osallistujien yksikköhinta vaihtuu. Esimerkki ei sisällä lisäkulujen tai ALV:n laskentaa.</p></>:mode==="quote"&&calculated.result?<><p className="budget-total-label">Kokonaishinta (sis. tarjouksen ALV)</p><p className="budget-total">{formatEuro(calculated.result.total)}</p><p className="budget-person">{formatEuro(calculated.result.perPerson)} / osallistuja</p><dl className="budget-breakdown"><div><dt>Koulutus {input.unit==="group"?`(${calculated.result.groups} ryhmää)`:`(${calculated.result.participants} hlö)`}</dt><dd>{formatEuro(calculated.result.training)}</dd></div><div><dt>Todistusten lisämaksut</dt><dd>{formatEuro(calculated.result.certificate)}</dd></div><div><dt>Matkakulut</dt><dd>{formatEuro(calculated.result.travel)}</dd></div><div><dt>Muut lisäkulut</dt><dd>{formatEuro(calculated.result.other)}</dd></div>{calculated.result.tax!==null?<><div><dt>Yhteensä ilman ALV:tä</dt><dd>{formatEuro(calculated.result.subtotal)}</dd></div><div><dt>ALV ({input.vat} %)</dt><dd>{formatEuro(calculated.result.tax)}</dd></div></>:null}</dl><p className="ea-help">{input.includesVat?"Syötetyt summat sisältävät tarjouksen ALV:n. Veron osuutta ei lasketa erikseen.":"ALV on laskettu syöttämälläsi prosentilla erittelyn yhteissummasta."} Osallistujahinta on pyöristetty senttiin.</p></>:<p className="budget-empty">{mode==="example"?"Tarkista osallistujamäärä, niin näet mallin hinnan.":input.training===""?"Syötä koulutuksen hinta, niin näet tarjouksen erittelyn ja hinnan osallistujaa kohti.":"Tarkista merkityt kentät. Virheellisistä arvoista ei lasketa hintaa."}</p>}</div>
      {smallCustom?<p className="plan-condition">EasyEA:n räätälöity koulutus edellyttää vähintään neljän henkilön ryhmää.</p>:null}{courseId==="ea2"?<p className="plan-condition">EA2 edellyttää aiempaa EA1-suoritusta.</p>:null}{validPeople!==null&&!smallCustom?<Link className="ea-button ea-button-primary" href={trainingLink("/yhteystiedot/",context)}>Jatka koulutuspyyntöön <span aria-hidden="true">↗</span></Link>:null}<p className="ea-help budget-transfer-note">Tarjouspyyntöön siirtyvät kurssi ja ryhmän koko. Syöttämäsi hintatiedot jäävät tähän laskuriin.</p></aside>
    </div><p className="calculator-footer">Mahdollisia Kela-korvauksia ei vähennetä laskelmasta. <Link href="/artikkelit/ensiapukoulutus-kela-korvaus/">Tutustu korvauksen ehtoihin.</Link></p>
  </section>;
}
