import { notFound } from "next/navigation";
import { pages, pageMetadata } from "../../lib/site";
import { PageContent } from "../../components/PageContent";
import { ContactForm } from "../../components/ContactForm";
import { Portrait, QuoteButton, FinalCTA } from "../../components/Shared";
import { CoursePlanner } from "../../components/CoursePlanner";
import { PriceCalculator } from "../../components/PriceCalculator";
import { readTrainingContext, trainingCourses, buyerRoles, trainingPackages, type QueryValues } from "../../lib/training";
export function generateStaticParams() {return [...pages.filter(p=>p.slug).map(p=>({slug:p.slug})),{slug:"privacy-policy"}];}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}) {const {slug}=await params; const page=pages.find(p=>p.slug===slug);return page?pageMetadata(page):{title:"Tietosuoja | EasyEA"};}
export default async function Page({params,searchParams}:{params:Promise<{slug:string}>,searchParams:Promise<QueryValues>}) {
 const {slug}=await params;
 if(slug==="privacy-policy")return <div className="ea-container ea-section privacy prose"><p className="eyebrow">TIETOSUOJA</p><h1 className="ea-h1 ea-h1-inner">Tietojen käsittely tällä sivustolla</h1><p>Tällä sivustolla yhteydenottolomake muodostaa sähköpostiluonnoksen omaan sähköpostiohjelmaasi. Lomaketietoja ei lähetetä EasyEA:lle tämän sivuston kautta eikä tallenneta sen tietokantaan. Voit tarkistaa ja lähettää viestin itse sähköpostiohjelmassasi.</p><h2>Yhteydenotto</h2><p>Sähköpostiin kirjoittamasi tiedot välittyvät vastaanottajalle vasta, kun lähetät viestin itse. Kysy yhteydenottosi tietojen käsittelystä: <a href="mailto:jaminyholm@easyea.fi">jaminyholm@easyea.fi</a>.</p><h2>Evästeet ja tekniset tiedot</h2><p>Sivustossa ei ole analytiikkaa, mainonnan seurantaa eikä upotettuja somepalveluita. Käyttöliittymä ei aseta evästeitä. Sivuston hosting-palvelu Vercel voi käsitellä pyynnön teknisiä tietoja, kuten IP-osoitetta, palvelun toimittamista ja tietoturvaa varten.</p><h2>Esittelyversion tiedot</h2><p>Tämä on EasyEA:n uuden verkkosivun esittelyversio. Ennen käyttöönottoa päädomainilla tietosuojaseloste täydennetään vahvistetuilla rekisterinpitäjän tiedoilla ja valitun yhteydenottopalvelun käytännöillä.</p></div>;
 const page=pages.find(p=>p.slug===slug);if(!page)notFound();
 if(slug==="yhteystiedot"){const query=await searchParams; const context=readTrainingContext(query);const kurssi=trainingCourses.find(c=>c.id===context.courseId)?.short||(typeof query.kurssi==="string"?query.kurssi:undefined);const chosenPackage=trainingPackages.find(p=>p.id===context.packageId);const role=buyerRoles.find(r=>r.id===context.roleId);const initialMessage=chosenPackage||role?[chosenPackage?`Koulutuspaketti: ${chosenPackage.name}`:"",role?`Tilaajan rooli: ${role.name}`:"","Haluan suunnitella lähikoulutuksen ryhmälleni ja asioida sähköpostilla."].filter(Boolean).join("\n"):undefined;return <><section className="ea-container ea-section contact-layout"><div className="contact-info"><p className="eyebrow">ALOITETAAN KESKUSTELU</p><h1 className="ea-h1 ea-h1-inner">{page.title}</h1><p className="ea-lead">{page.lead}</p><div className="contact-card"><h2 className="ea-h3">Jami Nyholm</h2><span>Ensihoitaja · EasyEA</span><a href="tel:+358504919444">050 491 9444 <span aria-hidden="true">↗</span></a><a href="mailto:jaminyholm@easyea.fi">jaminyholm@easyea.fi <span aria-hidden="true">↗</span></a><p>Kouvola · Toimialue koko Suomi</p></div><h2 className="ea-h3">Voit aloittaa myös kysymyksestä</h2><p>Kaikkien yksityiskohtien ei tarvitse olla valmiina. Jos pohdit kurssia, ajankohtaa tai ryhmän tarpeita, lähetä kysymys tai soita Jamille.</p></div><ContactForm initialCourse={kurssi} initialParticipants={context.participants} initialMessage={initialMessage}/></section></>;}
 if(slug==="kurssit"||slug==="ensiapukoulutus-hinta"){
  const context=readTrainingContext(await searchParams);
  const isCourses=slug==="kurssit";
  const lastHeading=page.body.lastIndexOf("## ");
  return <><section className="inner-hero ea-container catalog-hero"><div><p className="eyebrow">{isCourses?"EASYEA · ROOLIPOHJAISET KOULUTUSPAKETIT":"EASYEA · HINTALASKURI"}</p><h1 className="ea-h1 ea-h1-inner">{page.title}</h1><p className="ea-lead">{page.lead}</p><a className="ea-button ea-button-primary" href={isCourses?"#kurssivalinta":"#laskuri"}>{isCourses?"Valitse koulutuspaketti":"Avaa hintalaskuri"} <span aria-hidden="true">↓</span></a></div></section>{isCourses?<CoursePlanner initial={context}/>:<PriceCalculator initial={context}/>}<PageContent body={page.body.slice(0,lastHeading)}/><FinalCTA title="Suunnitellaan koulutus sähköpostilla" text="Valitse paketti ja kerro ryhmästäsi. Saat koulutuksen toteutuksesta ja hinnasta ehdotuksen sähköpostiin."/></>;
 }
 const lastHeading=page.body.lastIndexOf("## "); const finalBlock=page.body.slice(lastHeading).split("\n\n"); const ctaTitle=finalBlock[0].replace(/^## /,""); const ctaText=finalBlock[1] || "Kerro ryhmästäsi ja koulutustoiveestasi.";
 return <><section className={`inner-hero ea-container ${slug==="kouluttaja"?"with-portrait":""}`}><div><p className="eyebrow">EASYEA · {slug==="kurssit"?"ENSIAPUKURSSIT":slug==="kouluttaja"?"KOULUTTAJA":slug==="ensiapukurssi-kouvola"?"KOUVOLA":slug==="ensiapukoulutus-hinta"?"TARJOUS JA HINTA":"RYHMÄKOULUTUKSET"}</p><h1 className="ea-h1 ea-h1-inner">{page.title}</h1><p className="ea-lead">{page.lead}</p><QuoteButton/></div>{slug==="kouluttaja"&&<Portrait/>}</section><PageContent body={page.body.slice(0,lastHeading)}/><FinalCTA title={ctaTitle} text={ctaText}/></>;
}
