"use client";
import { useActionState, useState, type ChangeEvent, type ReactNode } from "react";
import { emptyParticipant, attendanceOptions, resultOptions, deliveryOptions, formatDate, nextStep, parseParticipants, type AdminState, type Participant, type Training } from "../../lib/admin";
import { saveTraining, saveParticipant, importParticipants } from "../../app/hallinta/actions";
type Action=(state:AdminState,data:FormData)=>Promise<AdminState>;
export function Notice({state}:{state:AdminState}) { return state.error?<p className="admin-notice admin-error" role="alert">{state.error}</p>:state.success?<p className="admin-notice admin-success" role="status">{state.success}</p>:null; }
export function Field({name,label,children,...props}:{name:string;label:string;children?:ReactNode;[key:string]:unknown}) { return <div className="ea-field"><label className="ea-label" htmlFor={name}>{label}</label>{children||<input className="ea-input" id={name} name={name} {...props}/>}</div>; }
export function TrainingForm({training,action=saveTraining}:{training?:Training;action?:Action}) {
  const [state,formAction,pending]=useActionState(action,{});
  const [fields,setFields]=useState({company:training?.company||"",course:training?.course||"",training_date:training?.training_date||"",code:training?.code||"",delivery_agreement:training?.delivery_agreement||"",admin_minutes:String(training?.admin_minutes||0),corrections:String(training?.corrections||0)});
  const change=(e:ChangeEvent<HTMLInputElement>)=>setFields(old=>({...old,[e.target.name]:e.target.value}));
  return <form action={formAction} className="admin-form"><Notice state={state}/>{training&&<><input type="hidden" name="id" value={training.id}/><input type="hidden" name="version" value={training.version}/></>}<div className="ea-form-grid">
    <Field name="company" label="Yritys tai yhteisö" required maxLength={500} value={fields.company} onChange={change}/>
    <Field name="course" label="Kurssi / toteutus" required maxLength={500} value={fields.course} onChange={change} placeholder="Esim. Hätäensiapu 4 h"/>
    <Field name="training_date" label="Koulutuspäivä" required type="date" value={fields.training_date} onChange={change}/>
    <Field name="code" label="Koulutuksen tunnus" required maxLength={50} value={fields.code} onChange={change} placeholder="Esim. EA-2026-001"/>
    <div className="ea-field-full"><Field name="delivery_agreement" label="Sovittu dokumenttien toimitus" required maxLength={500} value={fields.delivery_agreement} onChange={change} placeholder="Esim. hyväksytyt dokumentit yrityksen yhteyshenkilölle"/></div>
    <Field name="admin_minutes" label="Hallinnointiaika (min)" type="number" min={0} max={100000} step={1} value={fields.admin_minutes} onChange={change}/>
    <Field name="corrections" label="Korjausten määrä" type="number" min={0} max={100000} step={1} value={fields.corrections} onChange={change}/>
  </div><p className="admin-help">Yksi yritys ja koulutus per rekisteri. Koulutuksen tunnus liittää CSV-listan oikeaan koulutukseen.</p><button className="ea-button ea-button-primary" disabled={pending}>{pending?"Tallennetaan…":training?"Tallenna koulutuksen tiedot":"Luo koulutus"}</button></form>;
}
export function ParticipantForm({training,participant,action=saveParticipant,onClose}:{training:Training;participant?:Participant;action?:Action;onClose:()=>void}) {
  const p=participant||{...emptyParticipant,id:"",training_id:training.id,version:0};
  const [state,formAction,pending]=useActionState(action,{});
  const [fields,setFields]=useState({...p});const [approved,setApproved]=useState(!!p.document_approved_by);
  const change=(e:ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setFields(old=>({...old,[e.target.name]:e.target.value}));
  return <section className="admin-editor" aria-label="Osallistujan tiedot"><div className="admin-heading-row"><h3>{participant?"Muokkaa osallistujaa":"Lisää osallistuja"}</h3><button className="admin-text-button" type="button" onClick={onClose}>Sulje</button></div><form action={formAction} className="admin-form"><Notice state={state}/><input type="hidden" name="training_id" value={training.id}/><input type="hidden" name="id" value={p.id}/><input type="hidden" name="version" value={p.version}/><div className="ea-form-grid">
    <Field name="name" label="Nimi" required maxLength={160} value={fields.name} onChange={change}/><Field name="email" label="Sähköposti" required type="email" maxLength={254} value={fields.email} onChange={change}/>
    <Field name="attendance" label="Osallistuminen"><select className="ea-select" id="attendance" name="attendance" value={fields.attendance} onChange={change}>{attendanceOptions.map(s=><option key={s}>{s}</option>)}</select></Field>
    <Field name="result" label="Suoritus"><select className="ea-select" id="result" name="result" value={fields.result} onChange={change}>{resultOptions.map(s=><option key={s}>{s}</option>)}</select></Field>
    <div className="ea-field-full admin-help">Kun hyväksyt suorituksen, vahvistajaksi kirjataan kirjautunut hallinnoija ja päiväksi tämä päivä. Hyväksy vain kouluttajan vahvistama suoritus. {p.confirmed_by&&<strong>Kirjattu vahvistus: {p.confirmed_by}, {formatDate(p.confirmed_on)}.</strong>}</div>
    <div className="ea-field-full"><Field name="document_ref" label="Hyväksyttävän dokumentin tiedostoviite" maxLength={500} value={fields.document_ref} onChange={change} placeholder="Sisäinen tiedostoviite, ei julkinen henkilötietolinkki"/></div>
    <label className="admin-check ea-field-full"><input type="checkbox" name="approve_document" checked={approved} onChange={e=>setApproved(e.target.checked)}/> Olen tarkistanut dokumentin ja vahvistan sen hyväksynnän.</label>
    {p.document_approved_by&&<p className="admin-help ea-field-full">Hyväksyjä: {p.document_approved_by}, {formatDate(p.document_approved_on)}. Viitteen muuttaminen edellyttää uutta hyväksyntää.</p>}
    <Field name="delivery_method" label="Toimitustapa"><select className="ea-select" id="delivery_method" name="delivery_method" value={fields.delivery_method} onChange={change}>{deliveryOptions.map(s=><option key={s} value={s}>{s||"Ei vielä sovittu"}</option>)}</select></Field>
    <Field name="recipient" label="Sovittu vastaanottaja" maxLength={500} value={fields.recipient} onChange={change} placeholder="Sähköposti tai sovittu vastaanottaja"/>
    <Field name="delivered_on" label="Todellinen toimituspäivä" type="date" value={fields.delivered_on} onChange={change}/>
    <p className="admin-help">Kirjaa toimituspäivä vasta, kun hyväksytty dokumentti on toimitettu sovitusti. Paneeli ei lähetä dokumentteja tai myönnä todistuksia.</p>
  </div><button className="ea-button ea-button-primary" disabled={pending}>{pending?"Tallennetaan…":"Tallenna osallistuja"}</button></form></section>;
}
export function ParticipantList({training,participants,action=saveParticipant}:{training:Training;participants:Participant[];action?:Action}) {
  const [search,setSearch]=useState("");const [filter,setFilter]=useState("Kaikki");const [editing,setEditing]=useState<Participant|"new"|null>(null);const [saved,setSaved]=useState("");
  const active=participants.filter(p=>!p.archived);
  const visible=active.filter(p=>(p.name+" "+p.email).toLowerCase().includes(search.toLowerCase()) && (filter==="Kaikki" || (nextStep(training,p)==="Toimitettu") === (filter==="Toimitettu")));
  return <><div className="admin-heading-row"><div><h2>Osallistujat</h2><p className="admin-help">{active.length} / 100 osallistujaa. Avaa rivi käsitelläksesi suorituksen ja dokumentin.</p></div><button className="ea-button ea-button-primary" onClick={()=>setEditing("new")} disabled={active.length>=100}>+ Lisää osallistuja</button></div>{saved&&<p role="status" className="admin-notice admin-success">{saved}</p>}<div className="admin-filters"><Field name="participant-search" label="Hae osallistujaa" type="search" value={search} onChange={(e:React.ChangeEvent<HTMLInputElement>)=>setSearch(e.target.value)} placeholder="Nimi tai sähköposti"/><Field name="participant-filter" label="Käsittelytila"><select id="participant-filter" className="ea-select" value={filter} onChange={e=>setFilter(e.target.value)}>{["Kaikki","Työ odottaa","Toimitettu"].map(s=><option key={s}>{s}</option>)}</select></Field></div>
    <div className="admin-table-scroll" tabIndex={0} aria-label="Osallistujataulukko, vieritettävä tarvittaessa"><table className="admin-table"><caption className="sr-only">Koulutuksen {training.code} osallistujat</caption><thead><tr><th>Nimi ja sähköposti</th><th>Osallistuminen</th><th>Suoritus</th><th>Seuraava toimi</th><th><span className="sr-only">Muokkaus</span></th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td><strong>{p.name}</strong><span className="admin-cell-detail">{p.email}</span></td><td>{p.attendance}</td><td>{p.result}</td><td><span className={`admin-badge ${nextStep(training,p)==="Toimitettu"?"admin-badge-done":""}`}>{nextStep(training,p)}</span></td><td><button className="admin-text-button" onClick={()=>setEditing(p)} aria-label={`Muokkaa osallistujaa ${p.name}`}>Muokkaa ↗</button></td></tr>)}</tbody></table>{!visible.length&&<div className="admin-empty"><strong>{active.length?"Ei hakutuloksia":"Osallistujalista odottaa"}</strong><p>{active.length?"Muuta hakua tai käsittelytilaa.":"Lisää ensimmäinen osallistuja tai tuo yrityksen palauttama CSV-lista."}</p></div>}</div>
    {editing&&<ParticipantForm key={editing==="new"?"new":editing.id+"-"+editing.version} training={training} participant={editing==="new"?undefined:editing} action={async (state,data)=>{const result=await action(state,data);if(result.success){setSaved(result.success);setEditing(null);}return result;}} onClose={()=>setEditing(null)}/>}</>;
}
export function ImportForm({training,participants,action=importParticipants}:{training:Training;participants:Participant[];action?:Action}) {
  const [state,formAction,pending]=useActionState(action,{});const [csv,setCsv]=useState("");const [fileError,setFileError]=useState("");const [reviewed,setReviewed]=useState(false);
  const parsed=reviewed?parseParticipants(csv,training.code,participants.map(p=>p.email)):null;
  return <section className="admin-card" id="csv-tuonti"><h2>Tuo osallistujat CSV-listasta</h2><p className="admin-help">Tuo yksi yritys ja koulutus kerrallaan. Otsikot: Koulutuksen tunnus;Nimi;Sähköposti. Enintään 100 osallistujaa. Tyhjät rivit ohitetaan.</p><Notice state={state}/>{fileError&&<p role="alert" className="admin-notice admin-error">{fileError}</p>}<label className="ea-label" htmlFor="csv-file">Valitse CSV-tiedosto</label><input id="csv-file" type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setReviewed(false);setFileError("");if(file.size>200000){setFileError("Enimmäiskoko on 200 kt.");return;}try{setCsv(await file.text());}catch{setFileError("Tiedostoa ei voitu lukea.");}}}/><form action={formAction}><input type="hidden" name="training_id" value={training.id}/><Field name="csv" label="Tai liitä CSV:n sisältö"><textarea className="ea-textarea" id="csv" name="csv" value={csv} onChange={e=>{setCsv(e.target.value);setReviewed(false);}} rows={5} maxLength={200000} placeholder={`Koulutuksen tunnus;Nimi;Sähköposti\n${training.code};;`}/></Field><div className="admin-actions"><button type="button" className="ea-button ea-button-secondary" onClick={()=>setReviewed(true)}>Tarkista tuonti</button><button className="ea-button ea-button-primary" disabled={pending||!parsed||!!parsed.errors.length}>{pending?"Tuodaan…":"Tuo tarkistettu lista"}</button></div>{parsed&&<div className="admin-import-review" role="status">{parsed.errors.length?<><strong>Korjaa ennen tuontia</strong><ul>{parsed.errors.slice(0,10).map((s,i)=><li key={i}>{s}</li>)}</ul></>:<><strong>{parsed.rows.length} osallistujaa valmiina tuontiin</strong><ul>{parsed.rows.slice(0,5).map((p,i)=><li key={i}>{p.name} · {p.email}</li>)}</ul>{parsed.rows.length>5&&<p>Ja {parsed.rows.length-5} muuta osallistujaa.</p>}</>}</div>}</form></section>;
}
